### ISSUE TITLE
Elasticsearch memory limit

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-local-server#115]
Currently we give the elasticsearch service 1gb of memory for the docker container. This often results in start failures, where increasing it to 2gb will usually resolve it.

Per the docs on https://elk-docker.readthedocs.io/

> A minimum of 4GB RAM assigned to Docker
> Elasticsearch alone needs at least 2GB of RAM to run.

Apart from the fact that I think it's crazy you need 2GB of RAM to run ES, we should either increase our mem size to 2GB for ES, or look into ways to run ES with less memory.

**Comment by roborourke** [comment]
So far it's been an issue for CI environments and linux desktop. I opted for 1Gb as it worked for Windows and macOS, and was the lowest amount of memory that allowed it to consistently start up.

The problem is that Docker Desktop defaults to 2Gb ram for everything so if you haven't increased that on your system the other containers will fail to start or stop very quickly.

Ideally we find a way to run with less memory, but I recall you found it very slow locally with anything less than 1Gb.

There is a possible way to set memory usage programmatically by modifying this file `~/Library/Group Containers/group.com.docker/settings.json` and restarting docker, but we'd want to do the same for Windows. We'd also need to check how much overall memory the device has available.

**Comment by joehoyle** [comment]
Mmm interesting. I wonder how difficult it is to get ES to use less memory instead.

**Comment by mikeselander** [comment]
We're likely going to run into this on my current Altis-upgrade client as their Elasticsearch has a propensity to crash Chassis and they've had to give quite a bit more resources to ES to compensate. i don't think they'd have any issue with giving Docker more resources as a trade off for having a local closer to production.
