### ISSUE TITLE
Turn display_errors on by default

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-local-server#123]
Currently we use the `php.ini` from production, which has `display_errors = Off`. This means we don't get errors showing by default for fatals, which makes things like `wp cli` commands failing super difficult to debug.

I thinl we should change this to default on. I think we need to do this in the _actual_ php.ini because setting it in code falls into the "error happens before this code" problem.

Acceptance criteria:

- [x] Remove the line https://github.com/humanmade/altis-local-server/blob/461953201911a88f092969da24f003f89d25b081/inc/namespace.php#L52
- [x] In the module's `wp-config.php` file check if it's the CLI environment and if so call `ini_set( 
'display_errors', 'on' );`

To test restart the local server to apply the changes and confirm this works by calling an undefined function at the top of the `wp-config.php` file and running a CLI command. You can also `var_dump( ini_get( 'display_errors' ) )` to confirm the new default value.

**Comment by roborourke** [comment]
@joehoyle this can go in `docker/php.ini` - the ini file is mounted into the PHP docker image and automatically included. Currently used to enable mailhog.

**Comment by joehoyle** [comment]
Oh wow nice

**Comment by rmccue** [comment]
This should be set for the CLI environment (i.e. php-cli), but not for the web, as the logs command should be used for that instead.

FWIW, it's already turned on in the local-server bootstrap file, but we should actually remove this so that errors aren't displayed in a HTML context:
https://github.com/humanmade/altis-local-server/blob/461953201911a88f092969da24f003f89d25b081/inc/namespace.php#L52

**Comment by roborourke** [comment]
Fixed in #177
