### ISSUE TITLE
Remove restart on failure directive on Cavalcade container

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-local-server#164]
There's a problem that was previously worked around by setting the Cavalcade container to always restart.

This is because it would exit if WP wasn't installed yet which isn't possible because the containers must all be started before WP can be installed.

See #81 for background.

The changes in Cavalcade v2 should help to mitigate this issue so we need to test that and if successful remove the restart on failure configuration.

@kadamwhite does this more or less cover the issue you noticed with the Cavalcade container not stopping? I thought restart on failure should allow it to be stopped successfully.

**Comment by kadamwhite** [comment]
@roborourke if I manually stop the container, it does not seem to come back. But what I'm experiencing is that, after running local-server once, I then continued to see the cavalcade container spin up independently of any other docker commands or services, and would fail and continually restart. Because this interacts with my host's network configuration, it causes transient timeouts and intermittent but persistent ERR_NETWORK_RESET issues when trying to use the host OS until I manually `docker container stop {id}`.

**Comment by roborourke** [comment]
Alright, removing all `restart` directives from the docker compose file in an upcoming PR

**Comment by roborourke** [comment]
@kadamwhite for reference here did you stop local server using `composer server stop`?

**Comment by roborourke** [comment]
Issue was not explicitly stopping the containers using the command noted above and the use of `restart: on-failure` - this meant even if the docker daemon was restarted after a reboot of the computer for example the containers would start back up even though the rest of services would not.

**Comment by roborourke** [comment]
Tagged 3.0.5 with this fix https://github.com/humanmade/altis-local-server/releases/tag/3.0.5
