### ISSUE TITLE
Document importing SQL files

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-local-server#182]
Add docs on importing a database file into local-server. I think either piping like `cat file.sql | composer server cli db import -` or maybe `composer server cli db import file.sql` will work.

**Comment by kadamwhite** [comment]
`composer server cli -- db import file.sql` confirmed to work in my environments

**Comment by roborourke** [comment]
Fwiw that method only works if the SQL file is within the project root as that means it's also on the PHP server.

Importing databases is documented at the below URL currently however the example does not work because piping data in to the command that is executed on the container isn't supported at the moment.

https://github.com/humanmade/altis-local-server/blob/master/docs/cli.md#wp-cli

If there is a way to be able import db files from anywhere on the host machine that'd be ideal but for now we should update that documentation to add the step of moving the SQL file to the project root first.

**Comment by jazzsequence** [comment]
Would it be worth suggesting downloading the SQL file into an ignored folder (`ignore` is ignored by the default `.gitignore`) and then importing from there? ( e.g. `composer server cli -- db import ignore/file.sql`) Some variation on that is what I tend to do.

**Comment by roborourke** [comment]
@jazzsequence that can work, I'm not sure we need to recommend git ignoring the file necessarily as it's up to the project team. I've seen a pattern where some projects include a basic SQL file for bootstrapping the local environment for instance.

It could well be worth expanding on the note with regards to privacy and suggesting extra care is taken with any copy of a database that contains personal data.

**Comment by jazzsequence** [comment]
> It could well be worth expanding on the note with regards to privacy and suggesting extra care is taken with any copy of a database that contains personal data.

Good call 👍
