### ISSUE TITLE
💭 Permit project-specific php.ini changes

### ISSUE THREAD

**Issue by kadamwhite** [humanmade/altis-local-server#187]
**Describe the solution you'd like**

When working with `local-chassis`, we can pull in the chassis/phpini extension if we want to make one-off PHP settings changes (for example to customize debugging behavior, or toggle some setting locally as an experiment while working on features). It would be useful to be able to provide or autoload a project-level `.ini` file on `composer server start` which could be used to apply these settings to a specific site's containers.

Currently the only option is editing the `.ini` file inside this project's directory within the composer `vendor` directory tree, which is brittle. 

Any new file should ideally load _after_ what is, as of #185, called `zzz-altis.ini` so that settings may be overridden.

I'd accept arguments about why this is undesirable, as well, since Altis _does_ presuppose a certain PHP configuration. :slightly_smiling_face:

**Comment by roborourke** [comment]
As you mention the main reason not to do this is because the settings would differ on the production servers and you could end up wondering why things are behaving differently on local.

That said there are a subset of `php.ini` settings it would be useful to be able to set, specifically `xdebug.*` settings.

My first thought would be to see if it's possible to set these at run time using `ini_set()` but I know that's not always supported for all settings.

The work in #159 to generate the `docker-compose.yml` in PHP would enable us to do things like check for a custom ini file and add a volume mount if it exists which is probably the best option.

Before we get any further here though it'd be good to understand some the existing uses for custom ini settings on projects and whether there's a more specific use case for this.

**Comment by joehoyle** [comment]
Yeah +1 on not supporting this generically, though interested to understand the user-cases!

**Comment by kadamwhite** [comment]
Going to close this since I don't currently have a concrete use-case! We can reopen or open a new issue if one arises.
