### ISSUE TITLE
BUG: Changes made to PHP files are ignored

### ISSUE THREAD

**Issue by kucrut** [humanmade/altis-local-server#215]
I keep having to restart the PHP container after making changes to PHP files because otherwise they're not being picked up.

In my case, the issue is only occuring on MacOS and it's not always reproducible (ie. sometimes the container picks up the changes just fine).

Steps to reproduce:
1. Make a change to a PHP file (plugin/theme file).
2. Refresh browser to see the change.

Acceptance criteria:

- [ ] Changes made to PHP files should always be picked up without having to restart the container

**Comment by roborourke** [comment]
@kucrut so I noticed this or something like it on one or two of our larger projects. What I observed was not that the container needed restarting but that the file syncing was very very very slow, I believe due to the huge amount of files under a couple of instances of `node_modules` directories.

You could confirm this by not restarting the container but waiting for a while to see fi the changes propagate to the container after a minute or a few minutes. You could then further confirm by removing all instances of `node_modules` and seeing if the synchronisation speeds up.

I believe this is related to the issue @joehoyle raised #204 - we should document how to use the alternative file sync system for mac & windows. Not sure if we can support it out of the box but we could perhaps provide the configs for it and some docs.

**Comment by jennybeaumont** [comment]
Closing in favor of https://github.com/humanmade/altis-local-server/issues/204
