### ISSUE TITLE
Possible to run node dev server inside container?

### ISSUE THREAD

**Issue by kadamwhite** [humanmade/altis-local-server#251]
@rmccue @roborourke curious how complex something would be -- @johnbillion has worked around SSL issues with webpack dev server by running the server within Chassis, so that it can be accessible within the same domain and avoid cross-original or unsigned SSL errors. This would be broadly useful for local development, but i"m not sure how we'd go about doing so via local server.

Is it possible to run webpack-dev-server inside / on the same network as the docker container? I'm opening this issue to talk through the idea.

**Comment by roborourke** [comment]
Interesting idea. My immediate thought would be that any new service is its own container. Right now the problem is that we use local server for CI too and we don't have a way to provide separate CI and local dev configs.

Once we address that however a dev server container could be added quite easily to run behind the traefik proxy and benefit from the SSL certificate. I guess the thornier issue here is to what extent does that lock down the dev build in terms of tooling. Is there a single dev server package everything uses? Do we just need to mount `node_modules` into the node container and some other configured paths?

I like the idea. Depending on where we go with it and the limitations that we want or don't want will affect whether the implementation should be a separate composer dependency that integrates with the local server traefik proxy or whether it's a built in part of local server.

**Comment by rmccue** [comment]
Presuming this is primarily to use the SSL certificate, you could either use the [*.altis.dev certificate directly](https://github.com/humanmade/altis-local-server/blob/master/docker/sni/cert/altis.pem) (which is a real cert, just public) or run behind Traefik (which does the SSL termination); it doesn't need to be inside any existing container though, so far as I know.

**Comment by johnbillion** [comment]
BOOM I set this up without having to serve the dev-server from inside the container.

This is the devServer config:

```js
/** @type {WebpackDevServer.Configuration} */
const devServer = {
	host: '0.0.0.0',
	allowedHosts: [
		'*.altis.dev'
	],
	https: {
		key: fs.readFileSync( filePath( 'vendor/altis/local-server/docker/sni/key/altis.pem' ) ),
		cert: fs.readFileSync( filePath( 'vendor/altis/local-server/docker/sni/cert/altis.pem' ) ),
	},
};
```

And then the `publicPath` property can be set to whatever `.altis.dev` subdomain you're using for your project.

**Comment by rmccue** [comment]
Original question was answered, won't do for now.
