### ISSUE TITLE
Bug with sendmail substitute

### ISSUE THREAD

**Issue by mikelittle** [humanmade/altis-local-server#516]
I'm not sure which `sendmail` substitute we used, but it looks like it has a bug.

When Workflows sends an email that is caught by Mailhog, Mailhog fails to parse the sender and subject:
![Screenshot 2022-08-05 at 16.54.06.png](https://images.zenhubusercontent.com/5833067cb9dc3c622022491e/f39fb17c-f206-4b83-96de-25cd9c9e1ba4)

![Screenshot 2022-08-05 at 16.56.28.png](https://images.zenhubusercontent.com/5833067cb9dc3c622022491e/3380b32c-3fd7-4098-a08c-3f5ffb0ae6e5)

Looking at the raw email headers there is a rogue new line which splits the transport headers from those added by PHP.
![Screenshot 2022-08-05 at 16.57.16.png](https://images.zenhubusercontent.com/5833067cb9dc3c622022491e/865e2053-9980-4dc7-b1c1-a9fca3f74f8a)

This may be a bug in the `sendmail` clone or a misconfiguration. In particular, I have seen this type of erroer where a configuration file specifying headers had DOS line endings in a Unix environment.

**Comment by tomjn** [comment]
MailHog usually uses `mhsendmail` for this:

https://github.com/mailhog/mhsendmail

It hasn't been updated since 2016 though, I'm inclined to agree with the stray newline theory

**Comment by kovshenin** [comment]
Did some digging around this today, line endings are indeed a problem. I first tested the binary itself on both the 7.4 container and the 8.0 one. It worked fine under 7.4, which led me to test what PHP is actually sending to this binary. I wrote a little script to output all of stdin to a file:

```
# sendmail.sh
cat >/tmp/sendmail.out
```

And set it as the `PHP_SENDMAIL_PATH` in the Local Server config. Here's what I saw in PHP 7.4:

```
bash-5.0$ cat -e /tmp/sendmail.out 
To: foo@bar.org$
Subject: foo$
$
bar$
```

And here's what a PHP 8.0 container produced:

```
www-data@c02ccd184a67:/usr/src/app$ cat -e /tmp/sendmail.out 
To: foo@bar.org^M$
Subject: foo^M$
^M$
bar^M$
```

Turns out, the `mail()` function in PHP 8.0 has changed to output line endings to CRLF instead of LF, to be compliant with RFC2822. Unfortunately, the BusyBox sendmail (and other MTAs with a sendmail implementation) have not adapted to this change yet.

For example, when piping the sendmail.out file to the sendmail binary with verbose logging, here's what I see:

```
root@55bd64dfea16:/usr/src/app# sendmail -v -t -i -S mailhog:1025 < /tmp/sendmail.out 
sendmail: recv:'220 mailhog.example ESMTP MailHog'
sendmail: send:'EHLO 55bd64dfea16'
sendmail: recv:'250-Hello 55bd64dfea16'
sendmail: recv:'250-PIPELINING'
sendmail: recv:'250 AUTH PLAIN'
sendmail: send:'MAIL FROM:<root@55bd64dfea16>'
sendmail: recv:'250 Sender root@55bd64dfea16 ok'
sendmail: send:'RCPT TO:<foo@bar.org>'
sendmail: recv:'250 Recipient foo@bar.org ok'
sendmail: send:'DATA'
sendmail: recv:'354 End data with <CR><LF>.<CR><LF>'
'endmail: send:'To: foo@bar.org
'endmail: send:'Subject: foo
'endmail: send:'
'endmail: send:'bar
sendmail: send:'.'
sendmail: recv:'250 Ok: queued as SiknAX_Zl0flEr3zyuNz_HPqwx844ncOqc450xkNg6U=@mailhog.example'
sendmail: send:'QUIT'
sendmail: recv:'221 Bye'
```

You can see some of the `s` characters in `sendmail` have been replaced by a quote `'` denoting the end of the string that's being sent. That's a side effect of the ending being a stranded `\r` while the `\n` has been stripped. I think this is because of how `xmalloc_fgetline()` works in libbb, used by sendmail to read lines from stdin:

https://github.com/brgl/busybox/blob/abbf17abccbf832365d9acf1c280369ba7d5f8b2/libbb/get_line_from_file.c#L52-L62

Suggested workarounds include using a utility called `dos2unix` available in both apt, as well as BusyBox, to convert `\r\n` to `\n` when piping data into the sendmail binary. I tried it and it works, but now I think it's time to take a step back and have PHPMailer speak with MailHog directly over SMTP.

**Comment by kovshenin** [comment]
> MailHog usually uses `mhsendmail` for this:
> 
> https://github.com/mailhog/mhsendmail
> 
> It hasn't been updated since 2016 though, I'm inclined to agree with the stray newline theory

Discussed this briefly with @rmccue some time ago, but the 5MB binary kinda threw me off.
