### ISSUE TITLE
Cannot use v8js?

### ISSUE THREAD

**Issue by kadamwhite** [humanmade/altis-local-server#551]
I understood from the Altis documentation that we could use v8js, but I am unable to run code using that extension. The extension is not present when running `php -m` inside the container, and all attempts to use any of its functions fatal.

How can v8js theme code be tested locally? I also only see v8js in certain Altis instances, even running the same v12 version.

**Comment by rmccue** [comment]
This is a better question for support, but v8 is installed and available inside the PHP container as part of the container building process; if you're not seeing it be available, something is broken inside the PHP container. (We now use the [php-v8js Rust-based extension](https://github.com/joehoyle/php-v8js) rather than the older v8js extension which is no longer maintained.)

```
$ composer server shell
www-data@947f7f0b1f7a:/usr/src/app$ php -m | grep v8
php-v8
```

If you're not seeing this, best bet is to contact support to work through troubleshooting.

**Comment by rmccue** [comment]
Closing out as not replicable.
